/* ==========================================================================
   THE GREY MATTER - story data
   ========================================================================== */

export const STORIES = [
  {
    id: "drugs",
    category: "Drugs",
    title: "The Chemical Shortcut",
    blurb: "How substances hijack the brain's reward circuitry.",
    description: "A look at how psychoactive substances flood the brain's reward pathway with dopamine, why the high fades faster each time, and what tolerance actually does to a growing mind.",
    color: "#E8A33D",
    icon: "molecule",
    videoUrl: "https://www.youtube.com/embed/ao8L-0nSYzg",
    thumbnail: "/thumbnails/drugs.jpg",
  },
  {
    id: "pornography",
    category: "Pornography",
    title: "The Novelty Trap",
    blurb: "Why constant novelty rewires what feels rewarding.",
    description: "An exploration of how endless novel stimuli condition the brain to crave escalation, and why real-world intimacy can start to feel underwhelming by comparison.",
    color: "#E2536B",
    icon: "pulse",
    videoUrl: "https://www.youtube.com/embed/1aFfB2pXfoc",
    thumbnail: "/thumbnails/pornography.jpg",
  },
  {
    id: "technology",
    category: "Technology",
    title: "The Notification Loop",
    blurb: "The tiny dopamine hits behind every ping and swipe.",
    description: "Every buzz, badge and swipe is a small unpredictable reward. This story follows how variable-reward design keeps the brain checking back, and what it costs attention over time.",
    color: "#2FA5A0",
    icon: "spiral",
    videoUrl: "https://www.youtube.com/embed/HffWFd_6bJ0",
    thumbnail: "/thumbnails/technology.jpg",
  },
  {
    id: "stress",
    category: "Stress",
    title: "The Alarm That Won't Switch Off",
    blurb: "What happens when the body's alarm system stays on.",
    description: "Short bursts of stress sharpen focus. Chronic stress does the opposite. This story traces cortisol's path through the brain and body when the alarm never really turns off.",
    color: "#8B7EC8",
    icon: "wave",
    videoUrl: "https://www.youtube.com/embed/WuyPuH9ojCE",
    thumbnail: "/thumbnails/stress.jpg",
  },
  {
    id: "social-media",
    category: "Social Media",
    title: "The Mirror That Talks Back",
    blurb: "Comparison, validation, and the brain's need to belong.",
    description: "Likes and comments tap directly into the brain's ancient need for social approval. This story looks at what constant comparison does to self-image over time.",
    color: "#4FA6D8",
    icon: "orbit",
    videoUrl: "https://www.youtube.com/embed/7QQ_7zH_2Yg",
    thumbnail: "/thumbnails/social-media.jpg",
  },
  {
    id: "sleep",
    category: "Sleep Deprivation",
    title: "The Night the Brain Doesn't Clean Up",
    blurb: "Why a tired brain makes worse decisions than you think.",
    description: "Sleep is when the brain clears out the day's metabolic waste. This story follows what starts to break down when that nightly cleanup gets cut short.",
    color: "#6C6FC4",
    icon: "crescent",
    videoUrl: "https://www.youtube.com/embed/gedoSfZvBgE",
    thumbnail: "/thumbnails/sleep.jpg",
  },
  {
    id: "gaming",
    category: "Gaming",
    title: "The Quest That Never Ends",
    blurb: "Levels, loot and the loop that keeps you playing one more.",
    description: "Progress bars, loot drops and levels are engineered reward schedules. This story unpacks why just one more round is one of the hardest loops for the brain to walk away from.",
    color: "#8C9B4E",
    icon: "hex",
    videoUrl: "https://www.youtube.com/embed/Fw07b7H9Vbg",
    thumbnail: "/thumbnails/gaming.jpg",
  },
  {
    id: "anxiety",
    category: "Anxiety",
    title: "The Threat That Isn't There",
    blurb: "When the brain's warning system fires at nothing.",
    description: "Anxiety is a warning system built for real danger, misfiring at imagined ones. This story follows the loop between the amygdala and the racing thoughts it sets off.",
    color: "#D9713C",
    icon: "flicker",
    videoUrl: "https://www.youtube.com/embed/jRXkW4N8vOI",
    thumbnail: "/thumbnails/anxiety.jpg",
  },
];

export const ICONS = {
  molecule: '<svg viewBox="0 0 24 24"><circle cx="6" cy="7" r="2.4" fill="currentColor"/><circle cx="18" cy="7" r="2.4" fill="currentColor"/><circle cx="12" cy="18" r="2.4" fill="currentColor"/><path d="M8 8.3 10.5 15.8M16 8.3 13.5 15.8M8.4 6 15.6 6" stroke="currentColor" stroke-width="1.4" fill="none"/></svg>',
  pulse: '<svg viewBox="0 0 24 24"><path d="M2 12h4l2-7 4 14 3-10 2 3h5" stroke="currentColor" stroke-width="1.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  spiral: '<svg viewBox="0 0 24 24"><path d="M12 3a9 9 0 1 1-6.36 2.64" stroke="currentColor" stroke-width="1.6" fill="none" stroke-linecap="round"/><path d="M12 7a5 5 0 1 1-3.54 1.46" stroke="currentColor" stroke-width="1.6" fill="none" stroke-linecap="round"/><circle cx="12" cy="12" r="1.4" fill="currentColor"/></svg>',
  wave: '<svg viewBox="0 0 24 24"><path d="M2 12c2 0 2-6 4-6s2 12 4 12 2-12 4-12 2 12 4 12 2-6 4-6" stroke="currentColor" stroke-width="1.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  orbit: '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="2.2" fill="currentColor"/><ellipse cx="12" cy="12" rx="9" ry="3.6" stroke="currentColor" stroke-width="1.4" fill="none"/><ellipse cx="12" cy="12" rx="3.6" ry="9" stroke="currentColor" stroke-width="1.4" fill="none" transform="rotate(45 12 12)"/></svg>',
  crescent: '<svg viewBox="0 0 24 24"><path d="M15.5 4a8 8 0 1 0 4.5 14.5A8.5 8.5 0 0 1 15.5 4z" fill="currentColor"/></svg>',
  hex: '<svg viewBox="0 0 24 24"><path d="M12 2 20.5 7v10L12 22 3.5 17V7z" stroke="currentColor" stroke-width="1.4" fill="none" stroke-linejoin="round"/><path d="M12 8v8M8.5 10l7 4M15.5 10l-7 4" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/></svg>',
  flicker: '<svg viewBox="0 0 24 24"><path d="M13 2 4 14h6l-1 8 9-12h-6z" fill="currentColor"/></svg>',
};

export const svgIcon = (name) => ICONS[name] || ICONS.pulse;

export const CARD_MAP = {
  drugs: "/cards/drugs.svg",
  pornography: "/cards/pornography.svg",
  technology: "/cards/technology.svg",
  stress: "/cards/stress.svg",
  "social media": "/cards/emotion.svg",
  "sleep deprivation": "/cards/sleep.svg",
  gaming: "/cards/focus.svg",
  anxiety: "/cards/memory.svg",
  sleep: "/cards/sleep.svg",
  memory: "/cards/memory.svg",
  emotion: "/cards/emotion.svg",
  focus: "/cards/focus.svg",
};
